name: Generate needed formats from JSON
on:
  push:
    paths:
      - 'companies-support-isreal.json'
      - 'israel-companies-services.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install required libraries
        run: pip install -r requirements.txt

      - name: run the automated tasks
        run: python3 -B util/automated-tasks.py

      - name: add and commit generated file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          
          git add .
          git commit -m "automatically converted after editing companies-support-isreal.json and/or israel-companies-services.json"
      
      - name: print env vars
        run: env | sort

      - name: push the changes
        run: |
          git push https://${{ secrets.GIT_ACTION_TOKEN }}@github.com/AlwaysBeCalm/poykott.git


      # - name: push the generated file
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GIT_ACTION_TOKEN }}
      #     branch: main
      #     force_with_lease: true
